language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t abendeler/docker-travis-cli -f Dockerfile.dev .

script:
  - docker run -e CI=true abendeler/docker-travis-cli npm run test -- --coverage
